repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt (src only)
        entry: bash -c 'find src/ -name "*.rs" -exec rustfmt {} \;'
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy-lib
        name: cargo clippy (lib only)
        entry: cargo clippy --lib -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-check-lib
        name: cargo check (lib only)
        entry: cargo check --lib
        language: system
        types: [rust]
        pass_filenames: false

# Global configuration
default_stages: [pre-commit]
fail_fast: false
